CREATE DATABASE IF NOT EXISTS tptft;

USE tptft;

CREATE TABLE UNIT (
  id VARCHAR(50) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  cost INT NOT NULL,
  url_img VARCHAR(255) NOT NULL
);

CREATE TABLE ORIGIN (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    url_img VARCHAR(255) NOT NULL
);

CREATE TABLE UNITORIGIN (
    id INT PRIMARY KEY AUTO_INCREMENT,
    id_unit VARCHAR(50) NOT NULL,
    id_origin INT NOT NULL,
    FOREIGN KEY (id_unit) REFERENCES UNIT(id) ON DELETE CASCADE,
    FOREIGN KEY (id_origin) REFERENCES ORIGIN(id)
);
